### ISSUE TITLE
Reading package version from metadata

### ISSUE THREAD

**Issue by cuent** [abichinger/semantic-release-pypi#20]
When making a release, the version number is hard coded. However, `setup.cfg` allows reading the package version from [configuration files](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html?highlight=metadata#configuring-setup-using-setup-cfg-files) for example (if the pckg name is `my_package`):

setup.cfg
```yaml
[metadata]
version = attr: my_package.VERSION
```

**Problem:** current implementation will override the version in `setup.cfg` when it should override in `VERSION`.

**Comment by abichinger** [comment]
You probably have moved on by now, but I'm still going to comment on your request.

In order to override `my_package.VERSION` the plugin would first need to find the line of code where `VERSION` is assigned. As far as I know the assignment can be in any source file of the package.
The only method I can think of to accomplish this task is to use the [ast](https://docs.python.org/3/library/ast.html) module, but that seems rather difficult.

Can you think of any other idea to solve this?

`pyproject.toml` also allows dynamic metadata ([PEP 621](https://peps.python.org/pep-0621/#dynamic))
- Setuptools ([Dynamic Metadata](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#dynamic-metadata))
- [Flit](https://flit.pypa.io/en/stable/#usage)

**Comment by v1ack** [comment]
@abichinger as for now you are not checking if pyproject.project.version exists
https://github.com/abichinger/semantic-release-pypi/blob/3210d508d6cc1c9a561c5533b7f0499a6e35c3de/lib/py/set_version.py#L24
So dynamic version set is not possible for now

Maybe it's better to add option, which disables version change in local files, only build and upload package

**Comment by v1ack** [comment]
@abichinger yes, sounds good
Just to mention, there is another ability to run custom commands https://github.com/semantic-release/exec

**Comment by abichinger** [comment]
> Just to mention, there is another ability to run custom commands https://github.com/semantic-release/exec

@v1ack That's right, the difference will be that [normalizeVersion](https://github.com/abichinger/semantic-release-pypi/blob/3210d508d6cc1c9a561c5533b7f0499a6e35c3de/lib/util.ts#L8) is called before running the command set by `versionCmd`. `normalizeVersion` sanitizes some versions (e.g. `1.0.0-beta.1` becomes `1.0.0b1`). I have to admit, I'm not sure if `normalizeVersion` is still necessary, because using `1.0.0-beta.1` directly works when using hatch or setuptools as build backend.

https://github.com/abichinger/semantic-release-pypi/blob/3210d508d6cc1c9a561c5533b7f0499a6e35c3de/lib/util.ts#L8-L21

**Comment by abichinger** [comment]
[`versionCmd`](https://github.com/abichinger/semantic-release-pypi?tab=readme-ov-file#options) can now be used to dynamically set the version.
